module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#7c2e00",
        "on-secondary-fixed": "#1a1c1c",
        "on-surface": "#181c23",
        "on-tertiary-fixed": "#351000",
        "surface-container-low": "#f1f3fe",
        "inverse-surface": "#2d3039",
        "outline-variant": "#c1c6d7",
        "on-tertiary-container": "#fffbff",
        "inverse-on-surface": "#eef0fc",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#ecedf9",
        "inverse-primary": "#adc6ff",
        "on-background": "#181c23",
        "primary-fixed": "#d8e2ff",
        "surface-tint": "#005bc1",
        "secondary": "#5d5f5f",
        "on-secondary-fixed-variant": "#454747",
        "on-primary-fixed-variant": "#004493",
        "tertiary-fixed": "#ffdbcc",
        "outline": "#717786",
        "on-primary": "#ffffff",
        "surface-dim": "#d8d9e5",
        "surface-bright": "#f9f9ff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "secondary-container": "#dfe0e0",
        "error-container": "#ffdad6",
        "primary-container": "#0070eb",
        "on-secondary-container": "#616363",
        "primary": "#0058bc",
        "surface-variant": "#e0e2ed",
        "tertiary": "#9e3d00",
        "surface-container-high": "#e6e8f3",
        "tertiary-fixed-dim": "#ffb595",
        "on-primary-container": "#fefcff",
        "on-surface-variant": "#414755",
        "tertiary-container": "#c64f00",
        "on-secondary": "#ffffff",
        "surface": "#f9f9ff",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-highest": "#e0e2ed",
        "on-primary-fixed": "#001a41"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        lg: "24px",
        base: "8px",
        sm: "8px",
        xl: "32px",
        "margin-mobile": "20px",
        gutter: "16px",
        md: "16px"
      },
      fontFamily: {
        "headline-sm": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "label-md": ["Public Sans"],
        "body-md": ["Public Sans"],
        "label-sm": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "headline-md": ["Public Sans"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.5px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.1px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.3px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
